// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUWqiRq7NQ4spUvQfoHBNR_NtwtzgGo0',
    appId: '1:609759507371:web:2488da584799e6b1c3d8ee',
    messagingSenderId: '609759507371',
    projectId: 'counter-19b93',
    authDomain: 'counter-19b93.firebaseapp.com',
    databaseURL: 'https://counter-19b93-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'counter-19b93.appspot.com',
    measurementId: 'G-C43DZBTMQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFwEEEbIZpfgXU5Vusqn-kHn1TA5owHUQ',
    appId: '1:609759507371:android:cbed10a9f719632dc3d8ee',
    messagingSenderId: '609759507371',
    projectId: 'counter-19b93',
    databaseURL: 'https://counter-19b93-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'counter-19b93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAARb2VDeyIc5Fybkx7-stGhcubz31B1KI',
    appId: '1:609759507371:ios:f34bf77673ad89a1c3d8ee',
    messagingSenderId: '609759507371',
    projectId: 'counter-19b93',
    databaseURL: 'https://counter-19b93-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'counter-19b93.appspot.com',
    androidClientId: '609759507371-ni7m6tdks4u6d03c79nt6e9e896jf69d.apps.googleusercontent.com',
    iosClientId: '609759507371-t2cq71s0d8jiqeavip9d7io9fanigfmm.apps.googleusercontent.com',
    iosBundleId: 'it.ivlivs.counter',
  );
}
